// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: "https://m.media-amazon.com/images/I/61mIq2iJUXL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
    description: "Master the art of technical interviews with 189 programming questions and solutions. Learn essential data structures, algorithms, and problem-solving techniques used by top tech companies.",
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://m.media-amazon.com/images/I/81ANaVZk5LL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
    description: "Transform your life through tiny changes that deliver remarkable results. Discover proven strategies to build good habits, break bad ones, and master the tiny behaviors that lead to extraordinary outcomes.",
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    description: "Follow David Goggins' incredible journey from poverty and abuse to becoming a Navy SEAL and ultra-endurance athlete. Learn to master your mind and defy the odds through mental toughness and self-discipline.",
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://m.media-amazon.com/images/I/91nujEwIpYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    description: "Learn to focus without distraction in an increasingly connected world. Cal Newport presents rules for achieving peak productivity by training your mind to perform cognitively demanding tasks.",
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    description: "Grant Cardone reveals the secret to massive success by setting targets 10 times higher and taking 10 times more action. Break through average thinking and achieve extraordinary results in business and life.",
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://m.media-amazon.com/images/I/616OvChM3RL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
    description: "Master the art of persuasion and selling in every area of your life. Whether you're in sales or not, this book teaches essential skills for communicating effectively and getting what you want.",
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    description: "Challenge conventional wisdom about money and learn what the rich teach their kids about wealth that the poor and middle class do not. Discover the difference between working for money and having money work for you.",
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    description: "Understand the four ways people earn money and learn how to move from being an employee or self-employed to becoming a business owner or investor. Transform your financial future with this essential guide.",
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    description: "Discover the timeless laws of power used by history's most successful leaders. Learn strategies for gaining influence, protecting yourself, and navigating complex social dynamics in any environment.",
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: "https://m.media-amazon.com/images/I/91wOERyhh7L._UF1000,1000_QL80_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
    description: "Transform your life with a simple five-second decision that can break hesitation and self-doubt. Mel Robbins shares a powerful tool for taking action, building courage, and creating lasting change.",
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    description: "Dale Carnegie's timeless classic teaches fundamental techniques for handling people, winning them to your way of thinking, and changing people without arousing resentment. Essential skills for personal and professional success.",
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://m.media-amazon.com/images/I/51V3121nmkL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    description: "Robert Greene reveals the secrets of the world's greatest masters and shows how you can unlock your potential. Learn the path to mastery through analyzing the lives of historical and contemporary masters.",
  },
];